// Generated by Dev/generate-type.rb 09/04/2024 21:12

import TalkTalkSyntax

public struct AnalyzedCaseStmt: CaseStmt, AnalyzedStmt {
	public var body: [any TalkTalkSyntax.Stmt]
	
  public let wrapped: CaseStmtSyntax
	public var casesAnalyzed: [any AnalyzedExpr]
	public var bodyAnalyzed: AnalyzedBlockStmt

	public var inferenceType: InferenceType
	public var environment: Environment
	public var analyzedChildren: [any AnalyzedSyntax] {
		[bodyAnalyzed] + casesAnalyzed
	}

	// Delegate these to the wrapped node
	public var location: SourceLocation { wrapped.location }
	public var children: [any Syntax] { wrapped.children }
	public var cases: [any Expr] { wrapped.cases }

	public func accept<V>(_ visitor: V, _ scope: V.Context) throws -> V.Value where V: AnalyzedVisitor {
		try visitor.visit(self, scope)
	}

	public func accept<V: Visitor>(_ visitor: V, _ context: V.Context) throws -> V.Value {
		try visitor.visit(wrapped, context)
	}
}
