// Generated by Dev/generate-type.rb 08/13/2024 10:00

import TalkTalkSyntax

public struct AnalyzedIfStmt: IfStmt, AnalyzedStmt {
	let wrapped: any IfStmt

	public var typeID: TypeID
	public var analyzedChildren: [any AnalyzedSyntax] { fatalError("TODO") }

	// Delegate these to the wrapped node
	public var ifToken: Token { wrapped.ifToken }
	public var elseToken: Token? { wrapped.elseToken }
	public var condition: any Expr { wrapped.condition }
	public var consequence: any BlockExpr { wrapped.consequence }
	public var alternative: (any BlockExpr)? { wrapped.alternative }
	public var location: SourceLocation { wrapped.location }
	public var children: [any Syntax] { wrapped.children }

	public func accept<V>(_ visitor: V, _ scope: V.Context) throws -> V.Value where V: AnalyzedVisitor {
		try visitor.visit(self, scope)
	}

	public func accept<V: Visitor>(_ visitor: V, _ context: V.Context) throws -> V.Value {
		try visitor.visit(self, context)
	}
}
