typeName = ARGV[0] # protocol name like "FooExpr"
kind = ARGV[1] # expr/stmt/decl

syntaxName = "#{typeName}Syntax"
analyzedName = "Analyzed#{typeName}"

subdir = {
	"expr" => "Exprs",
	"stmt" => "Stmts",
	"decl" => "Decls"
}[kind] || abort("Unknown kind: #{kind}")

conformsTo = {
	"expr" => "Expr",
	"stmt" => "Stmt",
	"decl" => "Decl"
}[kind]

def write(path, contents)
	if File.exists?(path)
		abort("File already exists: #{path}")
	end

	File.open(path, "w+")	do |file|
		file.puts(contents)
	end
end

def insert(path, contents)
	line = File.read(path).lines.find_index { |line| line.include?("// GENERATOR_INSERTION") }

	if !line
		abort("Could not find insertion point for #{path}")
  end

	lines = File.read(path).lines
	lines.insert(line, contents + "\n")
	File.open(path, 'w+') { |file|
		file.puts(lines.join)
	}
end

syntaxPath = "Sources/TalkTalkSyntax/#{subdir}/#{typeName}.swift"
syntaxFile = <<~SWIFT
// Generated by Dev/generate-type.rb #{Time.now.strftime("%m/%d/%Y %H:%M")}

public protocol #{typeName}: #{conformsTo} {
	// Insert #{typeName} specific fields here
}

public struct #{typeName}Syntax: #{typeName} {
	// Where does this syntax live
	public var location: SourceLocation

	// Useful for just traversing the whole tree
	public var children: [any Syntax]

	// Let this node be visited by visitors
	public func accept<V: Visitor>(_ visitor: V, _ context: V.Context) throws -> V.Value {
		try visitor.visit(self, context)
	}
}
SWIFT

analyzedPath = "Sources/TalkTalkAnalysis/#{subdir}/Analyzed#{typeName}.swift"
analyzedFile = <<~SWIFT
// Generated by Dev/generate-type.rb #{Time.now.strftime("%m/%d/%Y %H:%M")}

import TalkTalkSyntax

public struct #{analyzedName}: #{typeName}, Analyzed#{kind.capitalize} {
	let wrapped: any #{typeName}

	public var typeID: TypeID
	public var analyzedChildren: [any AnalyzedSyntax] { fatalError("TODO") }

	// Delegate these to the wrapped node
	public var location: SourceLocation { wrapped.location }
	public var children: [any Syntax] { wrapped.children }

	public func accept<V>(_ visitor: V, _ scope: V.Context) throws -> V.Value where V: AnalyzedVisitor {
		try visitor.visit(self, scope)
	}

	public func accept<V: Visitor>(_ visitor: V, _ context: V.Context) throws -> V.Value {
		try visitor.visit(self, context)
	}
}
SWIFT

visitorRequirement = <<SWIFT
	func visit(_ expr: #{typeName}, _ context: Context) throws -> Value
SWIFT

analysisVisitorRequirement = <<SWIFT
	func visit(_ expr: Analyzed#{typeName}, _ context: Context) throws -> Value
SWIFT

write(syntaxPath, syntaxFile)
puts "wrote #{syntaxPath}"

write(analyzedPath, analyzedFile)
puts "wrote #{analyzedPath}"

insert("Sources/TalkTalkSyntax/Visitor.swift", visitorRequirement)
puts "added visitor requirement to Sources/TalkTalkSyntax/Visitor.swift"

insert("Sources/TalkTalkAnalysis/FileAnalysis/AnalysisVisitor.swift", analysisVisitorRequirement)
puts "added analysis visitor requirement to Sources/TalkTalkAnalysis/FileAnalysis/AnalysisVisitor.swift"

insert "Sources/TalkTalkAnalysis/FileAnalysis/SourceFileAnalyzer.swift", <<SWIFT
	public func visit(_ expr: any #{typeName}, _ context: Environment) throws -> any AnalyzedSyntax {
		#warning("TODO")
		fatalError("TODO")
	}

SWIFT
puts "added conformance to SourceFileAnalyzer"

insert "Sources/TalkTalkLSP/Handlers/TextDocumentSemanticTokensFull.swift", <<SWIFT
	func visit(_ expr: any #{typeName}, _ context: Context) throws -> [RawSemanticToken] {
		#warning("TODO")
		fatalError("TODO")
	}

SWIFT
puts "added conformance to SemanticTokensFull visitor"

insert "Sources/TalkTalkSyntax/Visitors/Formatter.swift", <<SWIFT
	public func visit(_ expr: any #{typeName}, _ context: Context) throws -> String {
		#warning("Generated by Dev/generate-type.rb")
		fatalError("TODO")
	}

SWIFT
puts "added conformance to Formatter visitor"

insert "Sources/TalkTalkSyntax/Visitors/ASTPrinter.swift", <<SWIFT
	@StringBuilder public func visit(_ expr: any #{typeName}, _ context: Context) throws -> String {
		dump(expr)
	}

SWIFT
puts "added conformance to ASTPrinter"

insert "Sources/TalkTalk/Interpreter.swift", <<SWIFT
	public func visit(_ expr: Analyzed#{typeName}, _ context: Scope) throws -> Value {
		#warning("Generated by Dev/generate-type.rb")
		fatalError("TODO")
	}

SWIFT
puts "added conformance to Interpreter.swift"

insert "Sources/TalkTalkCompiler/ChunkCompiler.swift", <<SWIFT
	public func visit(_ expr: Analyzed#{typeName}, _ context: Chunk) throws {
		#warning("Generated by Dev/generate-type.rb")
		fatalError("TODO")
	}
SWIFT
puts "added conformance to ChunkCompiler.swift"
