// Generated by Dev/generate-type.rb 09/29/2024 09:37

public protocol GroupedExpr: Expr {
	var expr: any Expr { get }
}

public struct GroupedExprSyntax: GroupedExpr {
	public var expr: any Expr

  // A unique identifier
  public var id: SyntaxID

	// Where does this syntax live
	public var location: SourceLocation

	// Useful for just traversing the whole tree
	public var children: [any Syntax] {
		[expr]
	}

	// Let this node be visited by visitors
	public func accept<V: Visitor>(_ visitor: V, _ context: V.Context) throws -> V.Value {
		try visitor.visit(self, context)
	}
}
