// Generated by Dev/generate-type.rb 08/20/2024 10:31

public protocol AssignmentStmt: Stmt {
	// Insert AssignmentStmt specific fields here
}

public struct AssignmentStmtSyntax: AssignmentStmt {
	public var assignee: any Expr
	public var value: any Expr
	
	// Where does this syntax live
	public var location: SourceLocation

	// Useful for just traversing the whole tree
	public var children: [any Syntax] { [assignee, value] }

	// Let this node be visited by visitors
	public func accept<V: Visitor>(_ visitor: V, _ context: V.Context) throws -> V.Value {
		try visitor.visit(self, context)
	}
}
