// Generated by Dev/generate-type.rb 09/17/2024 09:50

public protocol ForStmt: Stmt {
	// Insert ForStmt specific fields here
}

public struct ForStmtSyntax: ForStmt {
	public var element: any Syntax
	public var sequence: any Expr
	public var body: BlockStmtSyntax

	public var forToken: Token
	public var inToken: Token

	// A unique identifier
	public var id: SyntaxID

	// Where does this syntax live
	public var location: SourceLocation

	// Useful for just traversing the whole tree
	public var children: [any Syntax] {
		[element, sequence, body]
	}

	// Let this node be visited by visitors
	public func accept<V: Visitor>(_ visitor: V, _ context: V.Context) throws -> V.Value {
		try visitor.visit(self, context)
	}
}
