// Generated by Dev/generate-type.rb 10/02/2024 12:07

public protocol MethodDecl: Decl {
	// Insert MethodDecl specific fields here
	var nameToken: Token { get }
	var isStatic: Bool { get }
}

public struct MethodDeclSyntax: MethodDecl {
	public var funcToken: Token
	public var modifiers: [Token]
	public var nameToken: Token
	public var params: ParamsExprSyntax
	public var returns: TypeExprSyntax?
	public var body: BlockStmtSyntax
	public var isStatic: Bool

  // A unique identifier
  public var id: SyntaxID

	// Where does this syntax live
	public var location: SourceLocation

	// Useful for just traversing the whole tree
	public var children: [any Syntax] {
		if let returns {
			return [params, body, returns]
		} else {
			return [params, body]
		}
	}

	// Let this node be visited by visitors
	public func accept<V: Visitor>(_ visitor: V, _ context: V.Context) throws -> V.Value {
		try visitor.visit(self, context)
	}
}
