// Generated by Dev/generate-type.rb 10/01/2024 11:41

public protocol PropertyDecl: Decl {
	// Insert PropertyDecl specific fields here
	var name: Token { get }
	var isStatic: Bool { get }
}

public struct PropertyDeclSyntax: PropertyDecl {
	public var introducer: Token
	public var name: Token
	public var typeAnnotation: TypeExprSyntax?
	public var defaultValue: (any Expr)?
	public var modifiers: [Token]
	public var isStatic: Bool

  // A unique identifier
  public var id: SyntaxID

	// Where does this syntax live
	public var location: SourceLocation

	// Useful for just traversing the whole tree
	public var children: [any Syntax] {
		[typeAnnotation, defaultValue].compactMap(\.self)
	}

	// Let this node be visited by visitors
	public func accept<V: Visitor>(_ visitor: V, _ context: V.Context) throws -> V.Value {
		try visitor.visit(self, context)
	}
}
