// Generated by Dev/generate-type.rb 08/26/2024 13:05

public protocol FuncSignatureDecl: Decl {
	// Insert FuncSignatureDecl specific fields here
}

public struct FuncSignatureDeclSyntax: FuncSignatureDecl {
	public var funcToken: Token
	public var name: Token
	public var params: ParamsExprSyntax
	public var returnDecl: TypeExpr

  // A unique identifier
  public var id: SyntaxID

	// Where does this syntax live
	public var location: SourceLocation

	// Useful for just traversing the whole tree
	public var children: [any Syntax] {
		[
			params,
			returnDecl
		]
	}

	// Let this node be visited by visitors
	public func accept<V: Visitor>(_ visitor: V, _ context: V.Context) throws -> V.Value {
		try visitor.visit(self, context)
	}
}
