// Generated by Dev/generate-type.rb 08/26/2024 12:39

public protocol ProtocolDecl: Decl {
	// Insert ProtocolDefinition specific fields here
	var keywordToken: Token { get }
	var name: Token { get }
	var body: ProtocolBodyDeclSyntax { get }
	var typeParameters: [TypeExprSyntax] { get }
}

public struct ProtocolDeclSyntax: ProtocolDecl {
	// A unique identifier
	public var id: SyntaxID

	public var keywordToken: Token
	public var name: Token
	public var body: ProtocolBodyDeclSyntax
	public var typeParameters: [TypeExprSyntax]

	// Where does this syntax live
	public var location: SourceLocation

	// Useful for just traversing the whole tree
	public var children: [any Syntax] {
		typeParameters + [body]
	}

	// Let this node be visited by visitors
	public func accept<V: Visitor>(_ visitor: V, _ context: V.Context) throws -> V.Value {
		try visitor.visit(self, context)
	}
}
