// Generated by Dev/generate-type.rb 08/13/2024 10:00

public protocol IfStmt: Stmt {
	// Insert IfStmt specific fields here
	var ifToken: Token { get }
	var condition: any Expr { get }
	var consequence: any BlockStmt { get }
	var elseToken: Token? { get }
	var alternative: (any BlockStmt)? { get }
}

public struct IfStmtSyntax: IfStmt {
	public var id: SyntaxID
	public var ifToken: Token
	public var condition: any Expr
	public var consequence: any BlockStmt
	public var elseToken: Token?
	public var alternative: (any BlockStmt)?

	// Where does this syntax live
	public var location: SourceLocation

	// Useful for just traversing the whole tree
	public var children: [any Syntax]

	// Let this node be visited by visitors
	public func accept<V: Visitor>(_ visitor: V, _ context: V.Context) throws -> V.Value {
		try visitor.visit(self, context)
	}
}
