// Generated by Dev/generate-type.rb 09/27/2024 20:07

public protocol LogicalExpr: Expr {
	// Insert LogicalExpr specific fields here
}

public struct LogicalExprSyntax: LogicalExpr {
	public var lhs: any Expr
	public var rhs: any Expr
	public var op: Token

	// A unique identifier
	public var id: SyntaxID

	// Where does this syntax live
	public var location: SourceLocation

	// Useful for just traversing the whole tree
	public var children: [any Syntax] {
		[lhs, rhs]
	}

	// Let this node be visited by visitors
	public func accept<V: Visitor>(_ visitor: V, _ context: V.Context) throws -> V.Value {
		try visitor.visit(self, context)
	}
}
