#!/bin/bash

# Set up directories
mkdir -p tmp/swift-llvm
cd tmp/swift-llvm

# Clone repositories
git clone --depth=1 https://github.com/apple/swift.git
git clone --depth=1 https://github.com/llvm/llvm-project.git

# Build LLVM
cd llvm-project
mkdir build && cd build
cmake -G Ninja -DLLVM_ENABLE_PROJECTS="clang" -DCMAKE_BUILD_TYPE=Release ../llvm
ninja

# Go back to root directory
cd ../../

# Create build directory for Swift
mkdir build && cd build

# Configure the Swift build with CMake, setting the LLVM_DIR variable
cmake -G Ninja \
  -DLLVM_ENABLE_PROJECTS="clang;swift" \
  -DLLVM_TARGETS_TO_BUILD="X86" \
  -DCMAKE_BUILD_TYPE=Release \
  -DLLVM_ENABLE_ASSERTIONS=ON \
  -DLLVM_BUILD_LLVM_DYLIB=ON \
  -DLLVM_LINK_LLVM_DYLIB=ON \
  -DLLVM_DIR="../llvm-project/build/lib/cmake/llvm" \
  -DSWIFT_PATH_TO_LLVM_SOURCE="../llvm-project/llvm" \
  -DSWIFT_PATH_TO_LLVM_BUILD="../llvm-project/build" \
  -DSWIFT_PATH_TO_CMARK_SOURCE="../swift/cmark" \
  -DSWIFT_PATH_TO_CMARK_BUILD="$(pwd)/cmark" \
  -DSWIFT_PATH_TO_CLANG_SOURCE="../llvm-project/clang" \
  ../swift

# Build the project
ninja