// Generated by Dev/generate-type.rb 10/01/2024 11:41

import TalkTalkCore

public struct AnalyzedPropertyDecl: PropertyDecl, AnalyzedDecl {
  public let wrapped: PropertyDeclSyntax

	public var inferenceType: InferenceType
	public var environment: Environment
	public var analyzedChildren: [any AnalyzedSyntax] { [] }

	// Delegate these to the wrapped node
	public var location: SourceLocation { wrapped.location }
	public var children: [any Syntax] { wrapped.children }
	public var name: Token { wrapped.name }
	public var isStatic: Bool { wrapped.isStatic }

	public func accept<V>(_ visitor: V, _ scope: V.Context) throws -> V.Value where V: AnalyzedVisitor {
		try visitor.visit(self, scope)
	}

	public func accept<V: Visitor>(_ visitor: V, _ context: V.Context) throws -> V.Value {
		try visitor.visit(wrapped, context)
	}
}
