// Generated by Dev/generate-type.rb 08/22/2024 17:46

import TalkTalkSyntax

public struct AnalyzedDictionaryElementExpr: DictionaryElementExpr, AnalyzedExpr {
	public var keyAnalyzed: any Expr
	public var valueAnalyzed: any Expr
	let wrapped: any DictionaryElementExpr

	public var typeID: TypeID
	public var environment: Environment
	public var analyzedChildren: [any AnalyzedSyntax] { fatalError("TODO") }

	// Delegate these to the wrapped node
	public var location: SourceLocation { wrapped.location }
	public var children: [any Syntax] { wrapped.children }

	public func accept<V>(_ visitor: V, _ scope: V.Context) throws -> V.Value where V: AnalyzedVisitor {
		try visitor.visit(self, scope)
	}

	public func accept<V: Visitor>(_ visitor: V, _ context: V.Context) throws -> V.Value {
		try visitor.visit(self, context)
	}
}
