// Generated by Dev/generate-type.rb 09/04/2024 21:41

import TalkTalkSyntax

public struct AnalyzedEnumMemberExpr: EnumMemberExpr, AnalyzedExpr {
	public let wrapped: MemberExprSyntax
	public var receiverAnalyzed: AnalyzedIdentifierExpr?
	public var propertyAnalyzed: String
	public var paramsAnalyzed: [InferenceType]

	public var inferenceType: InferenceType
	public var environment: Environment
	public var analyzedChildren: [any AnalyzedSyntax] { [] }

	// Delegate these to the wrapped node
	public var location: SourceLocation { wrapped.location }
	public var children: [any Syntax] { wrapped.children }

	public func accept<V>(_ visitor: V, _ scope: V.Context) throws -> V.Value where V: AnalyzedVisitor {
		try visitor.visit(self, scope)
	}

	public func accept<V: Visitor>(_ visitor: V, _ context: V.Context) throws -> V.Value {
		try visitor.visit(wrapped, context)
	}
}
