// Generated by Dev/generate-type.rb 08/20/2024 09:32

import TalkTalkSyntax

public struct AnalyzedSubscriptExpr: SubscriptExpr, AnalyzedExpr {
	public var receiverAnalyzed: any AnalyzedExpr
	public var argsAnalyzed: [AnalyzedArgument]

	public let wrapped: SubscriptExprSyntax

	public var typeID: TypeID
	public var environment: Environment
	public var analysisErrors: [AnalysisError]
	public var analyzedChildren: [any AnalyzedSyntax] { [receiverAnalyzed] + argsAnalyzed.map(\.expr) }

	// Delegate these to the wrapped node
	public var receiver: any Expr { wrapped.receiver }
	public var location: SourceLocation { wrapped.location }
	public var children: [any Syntax] { wrapped.children }
	public var args: [CallArgument] { wrapped.args }

	public func accept<V>(_ visitor: V, _ scope: V.Context) throws -> V.Value where V: AnalyzedVisitor {
		try visitor.visit(self, scope)
	}

	public func accept<V: Visitor>(_ visitor: V, _ context: V.Context) throws -> V.Value {
		try visitor.visit(self, context)
	}
}
