// Generated by Dev/generate-type.rb 08/13/2024 10:30

public protocol StructDecl: Decl {
	var structToken: Token { get }
	var name: String { get }
	var nameToken: Token { get }
	var body: DeclBlockSyntax { get }
	var typeParameters: [TypeExprSyntax] { get }
	var conformances: [TypeExprSyntax] { get }
}

public struct StructDeclSyntax: StructDecl {
	public var id: SyntaxID
	public var structToken: Token
	public var name: String
	public var nameToken: Token
	public var body: DeclBlockSyntax
	public var typeParameters: [TypeExprSyntax]
	public var conformances: [TypeExprSyntax]

	// Where does this syntax live
	public var location: SourceLocation

	// Useful for just traversing the whole tree
	public var children: [any Syntax] {
		[body]
	}

	// Let this node be visited by visitors
	public func accept<V: Visitor>(_ visitor: V, _ context: V.Context) throws -> V.Value {
		try visitor.visit(self, context)
	}

	public var semanticLocation: SourceLocation? {
		[nameToken]
	}
}
