// Generated by Dev/generate-type.rb 08/20/2024 08:16

public protocol ArrayLiteralExpr: Expr {
	var exprs: [any Expr] { get }
}

public struct ArrayLiteralExprSyntax: ArrayLiteralExpr {
	public var id: SyntaxID

	public var exprs: [any Expr]

	// Where does this syntax live
	public var location: SourceLocation

	// Useful for just traversing the whole tree
	public var children: [any Syntax] { exprs }

	// Let this node be visited by visitors
	public func accept<V: Visitor>(_ visitor: V, _ context: V.Context) throws -> V.Value {
		try visitor.visit(self, context)
	}
}
