// Generated by Dev/generate-type.rb 08/22/2024 17:46

public protocol DictionaryElementExpr: Expr {
	// Insert DictionaryElementExpr specific fields here
	var key: any Expr { get }
	var value: any Expr { get }
}

public struct DictionaryElementExprSyntax: DictionaryElementExpr {
	public var id: SyntaxID
	public var key: any Expr
	public var value: any Expr
	// Where does this syntax live
	public var location: SourceLocation

	// Useful for just traversing the whole tree
	public var children: [any Syntax] { [key, value] }

	// Let this node be visited by visitors
	public func accept<V: Visitor>(_ visitor: V, _ context: V.Context) throws -> V.Value {
		try visitor.visit(self, context)
	}
}
