// Generated by Dev/generate-type.rb 08/20/2024 09:32

public protocol SubscriptExpr: Expr {
	// Insert SubscriptExpr specific fields here
	var receiver: any Expr { get }
	var args: [CallArgument] { get }
}

public struct SubscriptExprSyntax: SubscriptExpr {
	public var receiver: any Expr
	public var args: [CallArgument]

	// Where does this syntax live
	public var location: SourceLocation

	// Useful for just traversing the whole tree
	public var children: [any Syntax] { [receiver] + args }

	// Let this node be visited by visitors
	public func accept<V: Visitor>(_ visitor: V, _ context: V.Context) throws -> V.Value {
		try visitor.visit(self, context)
	}
}
