// Generated by Dev/generate-type.rb 09/29/2024 21:16

public protocol LetPattern: Syntax {
	// Insert LetPattern specific fields here
}

public struct LetPatternSyntax: LetPattern {
	public var letToken: Token
	public var name: Token
	public var value: (any Expr)?

  // A unique identifier
  public var id: SyntaxID

	// Where does this syntax live
	public var location: SourceLocation

	// Useful for just traversing the whole tree
	public var children: [any Syntax] {
		if let value { [value] } else { [] }
	}

	// Let this node be visited by visitors
	public func accept<V: Visitor>(_ visitor: V, _ context: V.Context) throws -> V.Value {
		try visitor.visit(self, context)
	}
}
